In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("Online Retail Data Set.csv")

In [3]:
df.shape

(541909, 8)

In [4]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [5]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [7]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [8]:
(df["Quantity"] < 0).sum()

np.int64(10624)

In [18]:
returns = df[df["Quantity"] < 0].copy()
returns.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,12/1/10 9:41,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,12/1/10 9:49,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,12/1/10 10:24,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,12/1/10 10:24,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,12/1/10 10:24,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,12/1/10 10:24,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,12/1/10 10:24,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,12/1/10 10:24,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,12/1/10 10:24,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,12/1/10 12:38,4.25,17897.0,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,-1,12/1/10 14:30,2.10,17841.0,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,-2,12/1/10 14:30,0.85,17841.0,United Kingdom
1973,C536548,22244,3 HOOK HANGER MAGIC GARDEN,-4,12/1/10 14:33,1.95,12472.0,Germany
1974,C536548,22242,5 HOOK HANGER MAGIC TOADSTOOL,-5,12/1/10 14:33,1.65,12472.0,Germany
1975,C536548,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-1,12/1/10 14:33,2.95,12472.0,Germany
1976,C536548,22892,SET OF SALT AND PEPPER TOADSTOOLS,-7,12/1/10 14:33,1.25,12472.0,Germany
1977,C536548,22654,DELUXE SEWING KIT,-1,12/1/10 14:33,5.95,12472.0,Germany
1978,C536548,22767,TRIPLE PHOTO FRAME CORNICE,-2,12/1/10 14:33,9.95,12472.0,Germany
1979,C536548,22333,RETROSPOT PARTY BAG + STICKER SET,-1,12/1/10 14:33,1.65,12472.0,Germany
1980,C536548,22245,"HOOK, 1 HANGER ,MAGIC GARDEN",-2,12/1/10 14:33,0.85,12472.0,Germany

In [10]:
returns["InvoiceNo"].head(20)

141     C536379
154     C536383
235     C536391
236     C536391
237     C536391
238     C536391
239     C536391
240     C536391
241     C536391
939     C536506
1441    C536543
1442    C536543
1973    C536548
1974    C536548
1975    C536548
1976    C536548
1977    C536548
1978    C536548
1979    C536548
1980    C536548
Name: InvoiceNo, dtype: str

In [11]:
df[df["Quantity"] < 0]["InvoiceNo"].astype(str).str.startswith("C").value_counts()

InvoiceNo
True     9288
False    1336
Name: count, dtype: int64

In [12]:
df[(df["Quantity"] < 0) & (~df["InvoiceNo"].astype(str).str.startswith("C"))].head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,12/1/10 16:50,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,12/2/10 14:42,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,12/3/10 15:30,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,12/3/10 15:30,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,12/3/10 15:30,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,12/3/10 15:32,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,12/3/10 15:33,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,12/3/10 15:33,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,12/3/10 15:34,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,12/3/10 15:35,0.0,NaN,United Kingdom
7198,537006,21648,NaN,-130,12/3/10 15:36,0.0,NaN,United Kingdom
7199,537007,21172,NaN,-80,12/3/10 15:36,0.0,NaN,United Kingdom
7200,537008,21161,NaN,-120,12/3/10 15:37,0.0,NaN,United Kingdom
7201,537009,84534B,NaN,-80,12/3/10 15:38,0.0,NaN,United Kingdom
7202,537010,22162,NaN,-40,12/3/10 15:38,0.0,NaN,United Kingdom
7203,537011,22139,NaN,-5,12/3/10 15:38,0.0,NaN,United Kingdom
7204,537012,21535,NaN,-12,12/3/10 15:39,0.0,NaN,United Kingdom
7205,537013,35965,NaN,-25,12/3/10 15:40,0.0,NaN,United Kingdom
7206,537014,21040,NaN,-20,12/3/10 15:40,0.0,NaN,United Kingdom
7207,537015,37464,NaN,-14,12/3/10 15:41,0.0,NaN,United Kingdom

In [13]:
returns = df[df["Quantity"] < 0].copy()

returns[["StockCode", "Description", "Quantity", "UnitPrice", "CustomerID"]].head(20)

,StockCode,Description,Quantity,UnitPrice,CustomerID
141,D,Discount,-1,27.50,14527.0
154,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,4.65,15311.0
235,22556,PLASTERS IN TIN CIRCUS PARADE,-12,1.65,17548.0
236,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,0.29,17548.0
237,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,0.29,17548.0
238,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,0.29,17548.0
239,21484,CHICK GREY HOT WATER BOTTLE,-12,3.45,17548.0
240,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,1.65,17548.0
241,22553,PLASTERS IN TIN SKULLS,-24,1.65,17548.0
939,22960,JAM MAKING SET WITH JARS,-6,4.25,17897.0
1441,22632,HAND WARMER RED RETROSPOT,-1,2.10,17841.0
1442,22355,CHARLOTTE BAG SUKI DESIGN,-2,0.85,17841.0
1973,22244,3 HOOK HANGER MAGIC GARDEN,-4,1.95,12472.0
1974,22242,5 HOOK HANGER MAGIC TOADSTOOL,-5,1.65,12472.0
1975,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-1,2.95,12472.0
1976,22892,SET OF SALT AND PEPPER TOADSTOOLS,-7,1.25,12472.0
1977,22654,DELUXE SEWING KIT,-1,5.95,12472.0
1978,22767,TRIPLE PHOTO FRAME CORNICE,-2,9.95,12472.0
1979,22333,RETROSPOT PARTY BAG + STICKER SET,-1,1.65,12472.0
1980,22245,"HOOK, 1 HANGER ,MAGIC GARDEN",-2,0.85,12472.0

In [23]:
purchases = df[df["Quantity"] > 0].copy()
returns = df[df["Quantity"] < 0].copy()

returns["ReturnQty"] = returns["Quantity"].abs()

matched = purchases.merge(
    returns,
    on=["CustomerID", "StockCode", "UnitPrice"],
    suffixes=("_purchase", "_return")
)

matched = matched[
    (matched["Quantity_purchase"] == matched["ReturnQty"]) &
    (matched["InvoiceDate_purchase"] < matched["InvoiceDate_return"])
].drop_duplicates(subset=["InvoiceNo_return"], keep="first")

matched.shape

(1093, 14)

In [19]:
len(matched)

6102

In [20]:
matched[[
    "InvoiceNo_purchase",
    "StockCode",
    "Quantity_purchase",
    "InvoiceNo_return",
    "Quantity_return",
    "CustomerID"
]].head(20)

,InvoiceNo_purchase,StockCode,Quantity_purchase,InvoiceNo_return,Quantity_return,CustomerID
0,536366,22632,6,C543611,-6,17850.0
1,536372,22632,6,C543611,-6,17850.0
2,536373,21071,6,C543611,-6,17850.0
3,536373,82483,2,C543611,-2,17850.0
4,536375,21071,6,C543611,-6,17850.0
5,536375,82483,2,C543611,-2,17850.0
6,536377,22632,6,C543611,-6,17850.0
7,536396,21071,6,C543611,-6,17850.0
8,536396,82483,2,C543611,-2,17850.0
9,536396,82494L,12,C543611,-12,17850.0
10,536398,22114,4,C538670,-4,13448.0
11,536399,22632,6,C543611,-6,17850.0
12,536406,21071,6,C543611,-6,17850.0
13,536407,22632,6,C543611,-6,17850.0
14,536437,21154,200,C548577,-200,13694.0
15,536533,22680,20,C538725,-20,16955.0
16,536540,C2,1,C540164,-1,14911.0
17,536557,21672,1,C541641,-1,17841.0
18,536557,21672,1,C561725,-1,17841.0
19,536557,22212,1,C568689,-1,17841.0

In [21]:
matched[[
    "InvoiceNo_purchase",
    "InvoiceDate_purchase",
    "StockCode",
    "Quantity_purchase",
    "InvoiceNo_return",
    "InvoiceDate_return",
    "Quantity_return",
    "CustomerID"
]].head(20)

,InvoiceNo_purchase,InvoiceDate_purchase,StockCode,Quantity_purchase,InvoiceNo_return,InvoiceDate_return,Quantity_return,CustomerID
0,536366,12/1/10 8:28,22632,6,C543611,2/10/11 14:38,-6,17850.0
1,536372,12/1/10 9:01,22632,6,C543611,2/10/11 14:38,-6,17850.0
2,536373,12/1/10 9:02,21071,6,C543611,2/10/11 14:38,-6,17850.0
3,536373,12/1/10 9:02,82483,2,C543611,2/10/11 14:38,-2,17850.0
4,536375,12/1/10 9:32,21071,6,C543611,2/10/11 14:38,-6,17850.0
5,536375,12/1/10 9:32,82483,2,C543611,2/10/11 14:38,-2,17850.0
6,536377,12/1/10 9:34,22632,6,C543611,2/10/11 14:38,-6,17850.0
7,536396,12/1/10 10:51,21071,6,C543611,2/10/11 14:38,-6,17850.0
8,536396,12/1/10 10:51,82483,2,C543611,2/10/11 14:38,-2,17850.0
9,536396,12/1/10 10:51,82494L,12,C543611,2/10/11 14:38,-12,17850.0
10,536398,12/1/10 10:52,22114,4,C538670,12/13/10 16:19,-4,13448.0
11,536399,12/1/10 10:52,22632,6,C543611,2/10/11 14:38,-6,17850.0
12,536406,12/1/10 11:33,21071,6,C543611,2/10/11 14:38,-6,17850.0
13,536407,12/1/10 11:34,22632,6,C543611,2/10/11 14:38,-6,17850.0
14,536437,12/1/10 12:12,21154,200,C548577,4/1/11 10:46,-200,13694.0
15,536533,12/1/10 13:31,22680,20,C538725,12/14/10 11:16,-20,16955.0
16,536540,12/1/10 14:05,C2,1,C540164,1/5/11 12:02,-1,14911.0
17,536557,12/1/10 14:41,21672,1,C541641,1/20/11 11:00,-1,17841.0
18,536557,12/1/10 14:41,21672,1,C561725,7/29/11 12:10,-1,17841.0
19,536557,12/1/10 14:41,22212,1,C568689,9/28/11 14:42,-1,17841.0

In [24]:
purchases = df[df["Quantity"] > 0].copy()
returns = df[df["Quantity"] < 0].copy()

returns["ReturnQty"] = returns["Quantity"].abs()

matched = purchases.merge(
    returns,
    on=["CustomerID", "StockCode", "UnitPrice"],
    suffixes=("_purchase", "_return")
)

matched = matched[
    (matched["Quantity_purchase"] == matched["ReturnQty"]) &
    (matched["InvoiceDate_purchase"] < matched["InvoiceDate_return"])
].drop_duplicates(subset=["InvoiceNo_return"], keep="first")

matched.shape

(1093, 14)

In [5]:
df_clean = df[df["Quantity"] >= 0].copy()

In [7]:
df_clean = df_clean[df_clean["UnitPrice"] >= 0].copy()

In [30]:
df_clean[["Quantity", "UnitPrice"]].eq(0).sum()

Quantity        0
UnitPrice    1179
dtype: int64

In [9]:
df_clean = df_clean[df_clean["UnitPrice"] > 0].copy()

In [32]:
df_clean.shape

(530104, 8)

In [33]:
df_clean[df_clean["CustomerID"].isnull()].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,12/1/10 14:32,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,12/1/10 14:32,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,12/1/10 14:32,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,12/1/10 14:32,1.66,NaN,United Kingdom
1447,536544,21790,VINTAGE SNAP CARDS,9,12/1/10 14:32,1.66,NaN,United Kingdom

In [17]:
df_customer = df_clean.dropna(subset=["CustomerID"]).copy()

In [35]:
df_customer.shape

(397884, 8)

In [11]:
df_clean["Revenue"] = df_clean["Quantity"] * df_clean["UnitPrice"]

In [22]:
df_clean["InvoiceDate"] = pd.to_datetime(df_clean["InvoiceDate"])

C:\Users\user\AppData\Local\Temp\ipykernel_10488\2779893561.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_clean["InvoiceDate"] = pd.to_datetime(df_clean["InvoiceDate"])

In [23]:
df_2011 = df_clean[df_clean["InvoiceDate"].dt.year == 2011].copy()

In [24]:
monthly_revenue = (
    df_2011.groupby(df_2011["InvoiceDate"].dt.month)["Revenue"]
    .sum()
    .reset_index()
)

monthly_revenue.columns = ["Month", "Revenue"]

In [25]:
monthly_revenue

    Month      Revenue
0       1   691364.560
1       2   523631.890
2       3   717639.360
3       4   537808.621
4       5   770536.020
5       6   761739.900
6       7   719221.191
7       8   759138.380
8       9  1058590.172
9      10  1154979.300
10     11  1509496.330
11     12   638792.680

In [43]:
monthly_revenue["Month"] = monthly_revenue["Month"].map({
    1: "January",
    2: "February",
    3: "March",
    4: "April",
    5: "May",
    6: "June",
    7: "July",
    8: "August",
    9: "September",
    10: "October",
    11: "November",
    12: "December"
})

In [44]:
monthly_revenue

        Month      Revenue
0     January   691364.560
1    February   523631.890
2       March   717639.360
3       April   537808.621
4         May   770536.020
5        June   761739.900
6        July   719221.191
7      August   759138.380
8   September  1058590.172
9     October  1154979.300
10   November  1509496.330
11   December   638792.680

In [11]:
df_q2 = df_clean[df_clean["Country"] != "United Kingdom"].copy()

In [30]:
df_clean["Revenue"] = df_clean["Quantity"] * df_clean["UnitPrice"]

In [34]:
df_q2 = df_clean[df_clean["Country"] != "United Kingdom"].copy()

In [35]:
country_revenue = (
    df_q2.groupby("Country")["Revenue"]
    .sum()
    .reset_index()
)

In [36]:
country_revenue

                 Country    Revenue
0              Australia  138521.31
1                Austria   10198.68
2                Bahrain     754.14
3                Belgium   41196.34
4                 Brazil    1143.60
5                 Canada    3666.38
6        Channel Islands   20450.44
7                 Cyprus   13590.38
8         Czech Republic     826.74
9                Denmark   18955.34
10                  EIRE  283453.96
11    European Community    1300.25
12               Finland   22546.08
13                France  209715.11
14               Germany  228867.14
15                Greece    4760.52
16             Hong Kong   15691.80
17               Iceland    4310.00
18                Israel    8135.26
19                 Italy   17483.24
20                 Japan   37416.37
21               Lebanon    1693.88
22             Lithuania    1661.06
23                 Malta    2725.59
24           Netherlands  285446.34
25                Norway   36165.44
26                Poland    7334.65
27              Portugal   33747.10
28                   RSA    1002.31
29          Saudi Arabia     145.92
30             Singapore   21279.29
31                 Spain   61577.11
32                Sweden   38378.33
33           Switzerland   57089.90
34                   USA    3580.39
35  United Arab Emirates    1902.28
36           Unspecified    4749.79

In [37]:
top10_countries = country_revenue.sort_values(
    by="Revenue",
    ascending=False
).head(10)

In [38]:
top10_countries

        Country    Revenue
24  Netherlands  285446.34
10         EIRE  283453.96
14      Germany  228867.14
13       France  209715.11
0     Australia  138521.31
31        Spain   61577.11
33  Switzerland   57089.90
3       Belgium   41196.34
32       Sweden   38378.33
20        Japan   37416.37

In [39]:
country_quantity = (
    df_q2.groupby("Country")["Quantity"]
    .sum()
    .reset_index()
)

In [40]:
top10_countries = top10_countries.merge(
    country_quantity,
    on="Country",
    how="left"
)

In [41]:
top10_countries

       Country    Revenue  Quantity
0  Netherlands  285446.34    200361
1         EIRE  283453.96    147173
2      Germany  228867.14    119261
3       France  209715.11    112103
4    Australia  138521.31     83901
5        Spain   61577.11     27940
6  Switzerland   57089.90     30629
7      Belgium   41196.34     23237
8       Sweden   38378.33     36083
9        Japan   37416.37     26016

In [42]:
customer_revenue = (
    df_customer.groupby("CustomerID")["Revenue"]
    .sum()
    .reset_index()
)

In [43]:
top10_customers = customer_revenue.sort_values(
    by="Revenue",
    ascending=False
).head(10)

In [44]:
top10_customers

      CustomerID    Revenue
1689     14646.0  280206.02
4201     18102.0  259657.30
3728     17450.0  194550.79
3008     16446.0  168472.50
1879     14911.0  143825.06
55       12415.0  124914.53
1333     14156.0  117379.63
3771     17511.0   91062.38
2702     16029.0   81024.84
0        12346.0   77183.60

In [45]:
country_demand = (
    df_q2.groupby("Country")["Quantity"]
    .sum()
    .reset_index()
)

In [46]:
country_demand = country_demand.sort_values(
    by="Quantity",
    ascending=False
)

In [47]:
df_clean.to_csv("online_retail_cleaned.csv", index=False)

In [49]:
df_clean.to_excel("online_retail_cleaned.xlsx", index=False)

In [50]:
monthly_revenue.to_excel("2011_monthly_revenue.xlsx", index=False)

top10_countries.to_excel("top10_countries.xlsx", index=False)

top10_customers.to_excel("top10_customers.xlsx", index=False)

country_demand.to_excel("country_demand.xlsx", index=False)

In [12]:
df_no_uk = df_clean[df_clean["Country"] != "United Kingdom"]

print("Total Revenue:", df_no_uk["Revenue"].sum())
print("Total Quantity Sold:", df_no_uk["Quantity"].sum())
print("Total Customers:", df_no_uk["CustomerID"].nunique())
print("Total Countries:", df_no_uk["Country"].nunique())

Total Revenue: 1641462.46
Total Quantity Sold: 925986
Total Customers: 418
Total Countries: 37